'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class clientes
    Public Property Id_Cliente As Integer
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property Dni As Integer
    Public Property telefono As Integer
    Public Property direccion As String
    Public Property email As String

End Class
