'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class detalle_factura
    Public Property id_detalle_factura As Integer
    Public Property id_factura As Integer
    Public Property cod_producto As Integer
    Public Property id_talle As Integer
    Public Property precio_detalle As Decimal
    Public Property cantidad_detalle As Integer
    Public Property importe_detalle As Decimal

End Class
