'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class factura
    Public Property id_factura As Integer
    Public Property id_usuario As Integer
    Public Property id_cliente As Integer
    Public Property fecha_factura As Nullable(Of Date)
    Public Property cantidad_factura As Short
    Public Property importe_factura As Decimal

    Public Overridable Property clientes As clientes
    Public Overridable Property detalles_factura As ICollection(Of detalles_factura) = New HashSet(Of detalles_factura)
    Public Overridable Property Usuarios As Usuarios

End Class
