'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class WorldShoes_Roman_RiosEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=WorldShoes_Roman_RiosEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Categoria() As DbSet(Of Categoria)
    Public Overridable Property clientes() As DbSet(Of clientes)
    Public Overridable Property detalles_factura() As DbSet(Of detalles_factura)
    Public Overridable Property empleados() As DbSet(Of empleados)
    Public Overridable Property factura() As DbSet(Of factura)
    Public Overridable Property Marcas() As DbSet(Of Marcas)
    Public Overridable Property Perfiles() As DbSet(Of Perfiles)
    Public Overridable Property Productos() As DbSet(Of Productos)
    Public Overridable Property talle() As DbSet(Of talle)
    Public Overridable Property talle_producto() As DbSet(Of talle_producto)
    Public Overridable Property Usuarios() As DbSet(Of Usuarios)

    Public Overridable Function MostrarTop5Vendidos() As ObjectResult(Of MostrarTop5Vendidos_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of MostrarTop5Vendidos_Result)("MostrarTop5Vendidos")
    End Function

    Public Overridable Function Top5ProductosVendidos() As ObjectResult(Of Top5ProductosVendidos_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Top5ProductosVendidos_Result)("Top5ProductosVendidos")
    End Function

    Public Overridable Function Top5ProductosVendidos2() As ObjectResult(Of Top5ProductosVendidos2_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Top5ProductosVendidos2_Result)("Top5ProductosVendidos2")
    End Function

    Public Overridable Function topProductos() As ObjectResult(Of topProductos_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of topProductos_Result)("topProductos")
    End Function

    Public Overridable Function VentasDiarias(fechaHoy As Nullable(Of Date)) As ObjectResult(Of VentasDiarias_Result)
        Dim fechaHoyParameter As ObjectParameter = If(fechaHoy.HasValue, New ObjectParameter("fechaHoy", fechaHoy), New ObjectParameter("fechaHoy", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of VentasDiarias_Result)("VentasDiarias", fechaHoyParameter)
    End Function

    Public Overridable Function VentasFiltradas(desde As Nullable(Of Date), hasta As Nullable(Of Date)) As ObjectResult(Of VentasFiltradas_Result)
        Dim desdeParameter As ObjectParameter = If(desde.HasValue, New ObjectParameter("desde", desde), New ObjectParameter("desde", GetType(Date)))

        Dim hastaParameter As ObjectParameter = If(hasta.HasValue, New ObjectParameter("hasta", hasta), New ObjectParameter("hasta", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of VentasFiltradas_Result)("VentasFiltradas", desdeParameter, hastaParameter)
    End Function

    Public Overridable Function VentasNetas(desde As Nullable(Of Date), hasta As Nullable(Of Date)) As ObjectResult(Of VentasNetas_Result)
        Dim desdeParameter As ObjectParameter = If(desde.HasValue, New ObjectParameter("desde", desde), New ObjectParameter("desde", GetType(Date)))

        Dim hastaParameter As ObjectParameter = If(hasta.HasValue, New ObjectParameter("hasta", hasta), New ObjectParameter("hasta", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of VentasNetas_Result)("VentasNetas", desdeParameter, hastaParameter)
    End Function

    Public Overridable Function VentasPorCategoria() As ObjectResult(Of VentasPorCategoria_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of VentasPorCategoria_Result)("VentasPorCategoria")
    End Function

    Public Overridable Function VentasPorCategoriaFecha(fdesde As Nullable(Of Date), fhasta As Nullable(Of Date)) As ObjectResult(Of VentasPorCategoriaFecha_Result)
        Dim fdesdeParameter As ObjectParameter = If(fdesde.HasValue, New ObjectParameter("fdesde", fdesde), New ObjectParameter("fdesde", GetType(Date)))

        Dim fhastaParameter As ObjectParameter = If(fhasta.HasValue, New ObjectParameter("fhasta", fhasta), New ObjectParameter("fhasta", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of VentasPorCategoriaFecha_Result)("VentasPorCategoriaFecha", fdesdeParameter, fhastaParameter)
    End Function

    Public Overridable Function VentasPorMarca() As ObjectResult(Of VentasPorMarca_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of VentasPorMarca_Result)("VentasPorMarca")
    End Function

    Public Overridable Function VentasPorMarcaFecha(fdesde As Nullable(Of Date), fhasta As Nullable(Of Date)) As ObjectResult(Of VentasPorMarcaFecha_Result)
        Dim fdesdeParameter As ObjectParameter = If(fdesde.HasValue, New ObjectParameter("fdesde", fdesde), New ObjectParameter("fdesde", GetType(Date)))

        Dim fhastaParameter As ObjectParameter = If(fhasta.HasValue, New ObjectParameter("fhasta", fhasta), New ObjectParameter("fhasta", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of VentasPorMarcaFecha_Result)("VentasPorMarcaFecha", fdesdeParameter, fhastaParameter)
    End Function

    Public Overridable Function VentasPorVendedor() As ObjectResult(Of VentasPorVendedor_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of VentasPorVendedor_Result)("VentasPorVendedor")
    End Function

    Public Overridable Function VentasPorVendedorFiltradoPorFecha(min As Nullable(Of Date), max As Nullable(Of Date)) As ObjectResult(Of VentasPorVendedorFiltradoPorFecha_Result)
        Dim minParameter As ObjectParameter = If(min.HasValue, New ObjectParameter("min", min), New ObjectParameter("min", GetType(Date)))

        Dim maxParameter As ObjectParameter = If(max.HasValue, New ObjectParameter("max", max), New ObjectParameter("max", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of VentasPorVendedorFiltradoPorFecha_Result)("VentasPorVendedorFiltradoPorFecha", minParameter, maxParameter)
    End Function

End Class
