'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class talle
    Public Property id_talle As Integer
    Public Property descripcion As String

    Public Overridable Property talle_producto As ICollection(Of talle_producto) = New HashSet(Of talle_producto)

End Class
