'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuarios
    Public Property id_Usuario As Integer
    Public Property Nombre As String
    Public Property Contraseña As String
    Public Property id_Perfil As Integer
    Public Property id_empleado As Integer
    Public Property estado_usuario As Integer

    Public Overridable Property empleados As empleados
    Public Overridable Property factura As ICollection(Of factura) = New HashSet(Of factura)
    Public Overridable Property Perfiles As Perfiles
    Public Overridable Property factura As ICollection(Of factura) = New HashSet(Of factura)

End Class
